name: macOS-build
on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  macos-build:
    name: Build app for macOS
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: python3 macOS-build/setup.py py2app
      - name: Create zip
        run: cd dist; zip -r ../FindOCVersion.app.zip FindOCVersion.app
      - name: Upload App to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FindOCVersion.app
          path: FindOCVersion.app.zip
