name: macOS-build
on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  macOS-build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install py2app
        run: |
          pip3 install py2app
      - name: Install tkinter
        run: |
          pip3 install tk  
      - name: Run py2app
        run: |
           python3 macOS-build/setup.py py2app
      - name: Upload app to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FindOCVersion macOS
          path: ./dist/