name: macOS-build
on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  macOS-build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install pyinstaller
        run: |
          pip3 install pyinstaller
      - name: Run pyinstaller
        run: |
          pyinstaller --windowed FindOCVersion.py
      - name: Upload app to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FindOCVersion macOS
          path: ./dist/