name: macOS-build
on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  macOS-build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Check Python install
        run: |
          which python3
          python3 --version
          which pip3
          pip3 --version

      - name: Check Python dependencies
        run: |
          python3 -c "from tkinter import __version__; print(__version__)"
          python3 -c "from tkinter.messagebox import __version__; print(__version__)"
          echo $DYLD_LIBRARY_PATH
          echo $DYLD_FRAMEWORK_PATH 

      - name: Install pyinstaller
        run: |
          pip3 install pyinstaller
      - name: Run pyinstaller
        run: |
          pyinstaller --windowed FindOCVersion.py
      - name: Upload app to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FindOCVersion macOS
          path: ./dist/