name: macOS-build
on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  macOS-build:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3.1'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Check Python install
        run: |
          which python3
          python3 --version
          which pip3
          pip3 --version
          
      - name: Install tkinter
        run: |
          pip3 install tk

      - name: Check tkinter install
        run: |
          python3 -c 'import tkinter; tcl = tkinter.Tcl(); print(tcl.call("info", "patchlevel"))'  

      - name: Install pyinstaller
        run: |
          pip3 install pyinstaller

      - name: Run pyinstaller
        run: |
          pyinstaller --windowed FindOCVersion.py
      - name: Upload app to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FindOCVersion macOS
          path: ./dist/